"""Script-based project scaffolds — no AI involved."""

from typing import Dict

VALID_STACKS = ("python-fastapi", "node-express", "static-html", "generic")

_PYTHON_GITIGNORE = """# Python
__pycache__/
*.py[cod]
*.egg-info/
.venv/
venv/
.env
*.log
.pytest_cache/
.mypy_cache/
dist/
build/
"""

_NODE_GITIGNORE = """node_modules/
.env
*.log
dist/
build/
.DS_Store
"""

_GENERIC_GITIGNORE = """.env
*.log
.DS_Store
Thumbs.db
"""


def get_scaffold_files(
    tech_stack: str,
    project_name: str,
    description: str = "",
) -> Dict[str, str]:
    """Return path -> content mapping for initial repo scaffold."""
    stack = (tech_stack or "generic").lower().strip()
    if stack not in VALID_STACKS:
        stack = "generic"

    readme = f"# {project_name}\n\n{description or 'Generated by Soda.'}\n"

    if stack == "python-fastapi":
        return {
            "README.md": readme,
            ".gitignore": _PYTHON_GITIGNORE,
            "requirements.txt": "fastapi>=0.115.0\nuvicorn[standard]>=0.34.0\n",
            "src/__init__.py": "",
            "src/main.py": (
                '"""Application entry point."""\n'
                "from fastapi import FastAPI\n\n"
                f'app = FastAPI(title="{project_name}")\n\n\n'
                '@app.get("/health")\n'
                "async def health():\n"
                '    return {"status": "ok"}\n'
            ),
            "Dockerfile": (
                "FROM python:3.12-slim\n"
                "WORKDIR /app\n"
                "COPY requirements.txt .\n"
                "RUN pip install --no-cache-dir -r requirements.txt\n"
                "COPY src/ ./src/\n"
                'CMD ["uvicorn", "src.main:app", "--host", "0.0.0.0", "--port", "8000"]\n'
            ),
        }

    if stack == "node-express":
        slug = project_name.lower().replace(" ", "-")
        return {
            "README.md": readme,
            ".gitignore": _NODE_GITIGNORE,
            "package.json": (
                "{\n"
                f'  "name": "{slug}",\n'
                '  "version": "1.0.0",\n'
                '  "private": true,\n'
                '  "scripts": {\n'
                '    "start": "node index.js"\n'
                "  },\n"
                '  "dependencies": {\n'
                '    "express": "^4.21.0"\n'
                "  }\n"
                "}\n"
            ),
            "index.js": (
                "const express = require('express');\n"
                "const app = express();\n"
                "app.get('/health', (_req, res) => res.json({ status: 'ok' }));\n"
                "const port = process.env.PORT || 3000;\n"
                "app.listen(port, () => console.log(`Listening on ${port}`));\n"
            ),
            "Dockerfile": (
                "FROM node:20-slim\n"
                "WORKDIR /app\n"
                "COPY package.json .\n"
                "RUN npm install --omit=dev\n"
                "COPY . .\n"
                'CMD ["npm", "start"]\n'
            ),
        }

    if stack == "static-html":
        return {
            "README.md": readme,
            ".gitignore": _GENERIC_GITIGNORE,
            "index.html": (
                "<!DOCTYPE html>\n"
                '<html lang="en">\n'
                "<head>\n"
                '  <meta charset="UTF-8">\n'
                f"  <title>{project_name}</title>\n"
                '  <link rel="stylesheet" href="style.css">\n'
                "</head>\n"
                "<body>\n"
                f"  <h1>{project_name}</h1>\n"
                f"  <p>{description or 'Generated by Soda.'}</p>\n"
                "</body>\n"
                "</html>\n"
            ),
            "style.css": (
                "body { font-family: system-ui, sans-serif; max-width: 720px; margin: 2rem auto; padding: 0 1rem; }\n"
            ),
        }

    return {
        "README.md": readme,
        ".gitignore": _GENERIC_GITIGNORE,
        ".editorconfig": (
            "root = true\n\n"
            "[*]\n"
            "indent_style = space\n"
            "indent_size = 2\n"
            "end_of_line = lf\n"
            "charset = utf-8\n"
        ),
    }
